import type { GenerationTask } from './types'

const now = Date.now()

export const SEED_TASKS: GenerationTask[] = [
  {
    id: 'task-001',
    prompt: 'Неоновый киберпанк-город под дождём, вид сверху',
    model: 'Midjourney v6',
    type: 'image',
    status: 'running',
    progress: 64,
    createdAt: now - 120_000,
    credits: 80,
    durationMs: 30_000,
  },
  {
    id: 'task-002',
    prompt: 'Дрон-облёт горного озера на рассвете, 5 сек',
    model: 'Kling 3.0',
    type: 'video',
    status: 'running',
    progress: 28,
    createdAt: now - 90_000,
    credits: 150,
    durationMs: 120_000,
  },
  {
    id: 'task-003',
    prompt: 'Сценарий рекламного ролика для кофейни, 30 секунд',
    model: 'GPT-4o',
    type: 'text',
    status: 'queued',
    progress: 0,
    createdAt: now - 60_000,
    credits: 6,
    durationMs: 8_000,
  },
  {
    id: 'task-004',
    prompt: 'Логотип для стартапа в сфере финтех, минимализм',
    model: 'Flux',
    type: 'image',
    status: 'queued',
    progress: 0,
    createdAt: now - 55_000,
    credits: 40,
    durationMs: 20_000,
  },
  {
    id: 'task-005',
    prompt: 'Анимированный баннер для интернет-магазина электроники',
    model: 'Kling 3.0',
    type: 'video',
    status: 'queued',
    progress: 0,
    createdAt: now - 40_000,
    credits: 120,
    durationMs: 90_000,
  },
  {
    id: 'task-006',
    prompt: 'Минималистичный логотип кофейни, бежевые тона',
    model: 'Flux',
    type: 'image',
    status: 'done',
    progress: 100,
    createdAt: now - 300_000,
    credits: 80,
    durationMs: 18_000,
  },
  {
    id: 'task-007',
    prompt: 'Краткое описание продукта для landing page SaaS',
    model: 'GPT-4o',
    type: 'text',
    status: 'done',
    progress: 100,
    createdAt: now - 600_000,
    credits: 4,
    durationMs: 5_000,
  },
  {
    id: 'task-008',
    prompt: 'Постер в стиле ретро-футуризм 80-х, космическая тема',
    model: 'Midjourney v6',
    type: 'image',
    status: 'done',
    progress: 100,
    createdAt: now - 900_000,
    credits: 80,
    durationMs: 25_000,
  },
  {
    id: 'task-009',
    prompt: 'Озвучка приветствия мужским голосом',
    model: 'ElevenLabs',
    type: 'audio',
    status: 'failed',
    progress: 0,
    createdAt: now - 200_000,
    credits: 30,
    error: 'Недостаточно кредитов',
    durationMs: 10_000,
  },
  {
    id: 'task-010',
    prompt: 'Постер в стиле ретро-футуризм 80-х',
    model: 'Seedream',
    type: 'image',
    status: 'cancelled',
    progress: 0,
    createdAt: now - 150_000,
    credits: 60,
    durationMs: 22_000,
  },
]
